### ISSUE TITLE
可以添加英语支持吗？

### ISSUE THREAD

**Issue by everyt** [Mxuan01/to-do-list-demo#1]
我今天发现了这个扩展，非常开心，但因为我不懂中文，使用起来有些困难，而且自己构建的话版本管理可能会比较麻烦。

**Comment by Mxuan01** [comment]
> 我今天发现了这个扩展，非常开心，但因为我不懂中文，使用起来有些困难，而且自己构建的话版本管理可能会比较麻烦。

I'm glad that you like this extension, and you are so considerate that submitted the issue in Chinese. But I'm still sorry, this extension is just a demo I wrote while writing a vscode webview extension development tutorial.

This extension is very simple, its data only exists locally and is not stored on any server. So even if this extension supports English, its functionality is still incomplete and cannot share the data between multiple vscode windows.

So if you want, you can clone this repository and try to implement the relevant functions yourself. You can easily do this by reading [vscode-webview-extension-guides](https://code.visualstudio.com/api/extension-guides/webview) and [vscode-publishing-extension](https://code.visualstudio.com/api/working-with-extensions/publishing-extension).

Best wishes.

**Comment by everyt** [comment]
Thanks for your kindness. I'll give it a try!
